mantra/mod_auth/controllers.py
# Auth module for Mantra Application

# ==================== #
#     Requirements     #
# ==================== #

# Import secrets module
import secrets

# Import dependencies from flask module
from flask import Blueprint, flash, redirect, render_template, request, url_for
# Import requirement of session management
from flask_login import current_user, login_required, login_user, logout_user

# Import elements from Mantra Application
from mantra import bcrypt, db
# Import forms required in the module
from mantra.mod_auth.forms import (LoginForm, RegistrationForm,
                                   UpdateProfileForm)
# Import utilities required in the module
from mantra.mod_auth.utils import save_picture
# Import models required in the module
from mantra.models import User

# ==================== #


# Define the blueprint: 'auth', set its url prefix: app.url/auth
mod_auth = Blueprint('auth', __name__, url_prefix='/auth')


# Set the routes and accepted methods

# ====================== #
#     Register Route     #
# ====================== #
@mod_auth.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    # If user already authenticated
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # If form is submitted
    if form.validate_on_submit():
        # Generate user_token
        random_token = secrets.token_hex(32)
        # Hashing user password
        hashed_pwd = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        # Create new User
        username = form.username.data
        name = form.name.data
        email = form.email.data
        password = hashed_pwd
        user_token = random_token
        new_user = User(username, name, email, password, user_token)
        # Store new user and apply changes to database
        db.session.add(new_user)
        db.session.commit()
        flash(f"A new account has been created!", 'success')
        return redirect(url_for('auth.login'))
    return render_template('auth/register.html', form=form,
                           title='Register', adds='register-page')


# =================== #
#     Login Route     #
# =================== #
@mod_auth.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    # If user already authenticated
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # If form is submitted
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        # If login success
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            # Session is for user
            login_user(user, remember=form.remember.data)
            flash(f"Login success!", 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        # If login is not success
        else:
            flash(f"These credentials do not match our records.", 'danger')
    return render_template('auth/login.html', form=form,
                           title='Login', adds='login-page')


# ==================== #
#     Logout Route     #
# ==================== #
@mod_auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))


# =================== #
#    Profile Route    #
# =================== #
@mod_auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    form = UpdateProfileForm()
    # If form is submitted
    if form.validate_on_submit():
        # Save profile picture
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        if form.new_password.data:
            hashed_pwd = bcrypt.generate_password_hash(form.new_password.data).decode('utf-8')
            current_user.password = hashed_pwd
        current_user.username = form.username.data
        current_user.name = form.name.data
        current_user.email = form.email.data
        # Apply changes to database
        db.session.commit()
        flash(f"Profile Updated!", 'success')
        return redirect(url_for('auth.profile'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.name.data = current_user.name
        form.email.data = current_user.email
    return render_template('auth/profile.html', form=form,
                           title='Profile', profile_menu='active',
                           icons='user')

mantra/mod_main/controllers.py
# Main module for Mantra Application

# ==================== #
#     Requirements     #
# ==================== #

# Import dependencies from flask module
from flask import Blueprint, jsonify, redirect, render_template, url_for
# Import requirement of session management
from flask_login import current_user, login_required

# Import forms required in the module
from mantra.mod_main.forms import StatisticYearForm
# Import utilities required in the module
from mantra.mod_main.utils import (generate_monthly_statistic,
                                   generate_platform_statistic)
# Import models required in the module
from mantra.models import ScannedWebSchema

# ==================== #


# Define the blueprint: 'main', set its url prefix: app.url/
mod_main = Blueprint('main', __name__, url_prefix='/')


# Set the routes and accepted methods

# ================== #
#     Home Route     #
# ================== #
@mod_main.route('/', methods=['GET', 'POST'])
@mod_main.route('/home', methods=['GET', 'POST'])
@login_required
def home():
    form = StatisticYearForm()
    return render_template('main/home.html', title='Dashboard', form=form,
                           home_menu='active', icons='pie-chart')


# =========================== #
#     Documentation Route     #
# =========================== #
@mod_main.route('/documentation')
@login_required
def documentation():
    return render_template('main/documentation.html', title='Documentation',
                           doc_menu='active', icons='book')


# ============================= #
#     About Developer Route     #
# ============================= #
@mod_main.route('/developers')
@login_required
def developers():
    return render_template('main/developer.html', title='Developers',
                           dev_menu='active', icons='legal')


# =========================== #
#     Documentation Route     #
# =========================== #
@mod_main.route('/pentest_chart/<int:year>')
@login_required
def pentest_chart(year):
    # scanned_webs_schema = ScannedWebSchema(many=True)
    scanned_webs = current_user.scanned_webs
    web_list = []
    for web in scanned_webs:
        if web.date_created.year == year:
            data = web
            web_list.append(data)
    platform_stat = generate_platform_statistic(web_list)
    monthly_stat = generate_monthly_statistic(web_list)
    obj = {
        "platform_statistic": platform_stat,
        "monthly_statistic": monthly_stat,
    }
    return jsonify(statistic=obj)

mantra/mod_pentest/controllers.py
# Penetration testing module for Mantra Application

# ==================== #
#     Requirements     #
# ==================== #

# Import json module
import json
# Import Thread module
from threading import Thread

# Import pdfkit module
import pdfkit
# Import requests module
import requests
# Import dependencies from flask module
from flask import (Blueprint, abort, flash, jsonify, make_response, redirect,
                   render_template, url_for)
# Import requirement of session management
from flask_login import current_user, login_required

# Import elements from Mantra Application
from mantra import db
# Import forms required in the module
from mantra.mod_pentest.forms import PentestForm
# Import utilities required in the module
from mantra.mod_pentest.utils import Scanner
# Import models required in the module
from mantra.models import ScannedWeb, ScannedWebSchema
# Import url host and port
from run import host, port

# ==================== #


# Define the blueprint: 'autotest', set its url prefix: app.url/autotest
mod_pentest = Blueprint('autotest', __name__, url_prefix='/autotest')


# Set the routes and accepted methods

# ========================= #
#     New Pentest Route     #
# ========================= #
@mod_pentest.route('/pentest_new', methods=['GET', 'POST'])
@login_required
def pentest_new():
    form = PentestForm()
    if form.validate_on_submit():
        data_title = form.title.data
        data_url = form.url.data
        if not (data_url.startswith('http://') or data_url.startswith('https://')):
            flash(f"Invalid URL!", 'danger')
            return redirect(url_for('autotest.pentest_results'))
        data_description = form.description.data
        user_token = current_user.user_token
        data = {"title": data_title,
                "url": data_url,
                "description": data_description,
                "user_token": user_token}
        Thread(target=Scanner.scan, args=(data,)).start()
        flash(f"Pentest is being conducted. Please check the result.", 'warning')
        return redirect(url_for('autotest.pentest_results'))
    return render_template('pentest/pentest_new.html', title='Pentest',
                           pentest_menu='active', pentest_new='active',
                           icons='gears', form=form)


# ========================= #
#     All Results Route     #
# ========================= #
@mod_pentest.route('/pentest_results')
@login_required
def pentest_results():
    return render_template('pentest/pentest_results.html', title='Pentest',
                           pentest_menu='active', pentest_results='active',
                           icons='gears')


# ============================ #
#     Pentest Result Route     #
# ============================ #
@mod_pentest.route('/pentest_result/<web_id>')
@login_required
def pentest_result(web_id):
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    else:
        if web.platform.type == 'wordpress':
            return render_template('pentest/wp_pentest_result.html', title='Pentest',
                                   pentest_menu='active', pentest_results='active',
                                   icons='gears', web=web)
        elif web.platform.type == 'joomla':
            return render_template('pentest/joom_pentest_result.html', title='Pentest',
                                   pentest_menu='active', pentest_results='active',
                                   icons='gears', web=web)


# =========================================== #
#     Retrieves All Results Data from API     #
# =========================================== #
@mod_pentest.route('/get_results_data')
@login_required
def get_all_data():
    scanned_webs_schema = ScannedWebSchema(many=True)
    all_webs = current_user.scanned_webs
    result = scanned_webs_schema.dump(all_webs).data
    sent = jsonify(data=result)
    return sent


# ======================================= #
#     Retrieves raw_result of the web     #
# ======================================= #
@mod_pentest.route('/get_raw_result/<web_id>')
@login_required
def get_one_result(web_id):
    scanned_web_schema = ScannedWebSchema()
    data = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    web = scanned_web_schema.dump(data).data
    raw_result = web['raw_result']
    result = json.loads(raw_result)
    sent = jsonify(result)
    return sent


# =================================== #
#     Delete Pentest Result Route     #
# =================================== #
@mod_pentest.route('/pentest_delete/<web_id>', methods=['POST'])
@login_required
def pentest_delete(web_id):
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    db.session.delete(web)
    db.session.commit()
    flash(f"Pentest result has been deleted!", 'success')
    return redirect(url_for('autotest.pentest_results'))


# =============================== #
#     Create PDF Result Route     #
# =============================== #
@mod_pentest.route("/to_pdf/<web_id>")
@login_required
def to_pdf(web_id):
    domain = f"{host}:{port}"
    scanned_web_schema = ScannedWebSchema()
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    else:
        if web.platform.type == 'wordpress':
            data = scanned_web_schema.dump(web).data
            raw_result = data['raw_result']
            result = json.dumps(raw_result)
            rendered = render_template(
                'pentest/to_wp_pdf.html', web=web, result=result, domain=domain)
        elif web.platform.type == 'joomla':
            data = scanned_web_schema.dump(web).data
            raw_result = data['raw_result']
            result = json.dumps(raw_result)
            rendered = render_template(
                'pentest/to_joom_pdf.html', web=web, result=result, domain=domain)

        pdf = pdfkit.from_string(rendered, False)
        response = make_response(pdf)
        response.headers['Content-Type'] = 'application/pdf'
        # response.headers['Content-Disposition'] = f'inline; filename={web_id}.pdf'
        response.headers['Content-Disposition'] = f'attachment; filename={web_id}.pdf'

        return response

mantra/templates/includes/_footer.html
<!-- Main Footer -->
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <strong>Version</strong> 1.0.0
    </div>
    <strong>
        &copy; Mantra
        <span class="text-muted"> | an automated penetration testing web-based application.</span>
    </strong>
</footer>
<!-- /.Main Footer -->

mantra/templates/includes/_formHelper.html
{% macro render_field(field) %}
    <!-- Form Helper -->
    {{ field(**kwargs)|safe }}
    {% if field.errors %}
        {% for error in field.errors %}
            <span class="help-inline text-red">{{ error }}</span>
        {% endfor %}
    {% endif %}
    <!-- /.Form Helper -->
{% endmacro %}

mantra/templates/includes/_header.html
<!-- Main Header -->
<header class="main-header">
    <!-- Mantra Logo -->
    <a href="{{ url_for('main.home') }}" class="logo">
        <!-- Mantra logo for sidebar mini -->
        <span class="logo-mini"><b>M</b>/<i>p</i></span>
        <!-- Mantra logo for regular state -->
        <span class="logo-lg"><b>Mantra</b> | <i>project</i></span>
    </a>
    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle Navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account Menu -->
                <li class="dropdown user user-menu">
                    <!-- Menu Toggle Button -->
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <!-- The user image in the navbar-->
                        <img src="{{ url_for('static', filename = 'dist/img/' + current_user.image_file) }}"
                            class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ current_user.username }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- The user image in the menu -->
                        <li class="user-header">
                            <img src="{{ url_for('static', filename = 'dist/img/' + current_user.image_file) }}"
                                class="img-circle" alt="User Image">
                            <p>
                                {{ current_user.username }}
                                <small>{{ current_user.email }}</small>
                            </p>
                        </li>
                        <!-- Menu Body -->
                        <li class="user-body">
                            <div class="pull-left">
                                <a href="{{ url_for('auth.profile') }}" class="btn btn-default btn-flat">Profile</a>
                            </div>
                            <div class="pull-right">
                                <a href="{{ url_for('auth.logout') }}" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>
<!-- /.Main Header -->

mantra/templates/includes/_messages.html
{% with messages = get_flashed_messages(with_categories = true) %}
    {% if messages %}
        {% for category, message in messages %}
            <!-- Message -->
            <div class="alert alert-{{category}} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-warning"></i>{{ category }}!</h4>
                {{ message }}
            </div>
            <!-- /.Message -->
        {% endfor %}
    {% endif %}
{% endwith %}

mantra/templates/includes/_sidebar.html
<!-- Main Sidebar -->
<aside class="main-sidebar">
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ url_for('static', filename = 'dist/img/' + current_user.image_file) }}"
                    class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ current_user.username }}</p>
                <!-- Status -->
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>
        <!-- /.Sidebar user panel -->
        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header text-center"><b>MANTRA NAVIGATION</b></li>
            <!-- Dashboard Menu -->
            <li class="{{home_menu}}">
                <a href="{{ url_for('main.home') }}">
                    <i class="fa fa-pie-chart"></i>
                    <span>Dashboard</span>
                </a>
            </li>
            <!-- /.Dashboard Menu -->
            <!-- Pentest Menu -->
            <li class="treeview {{pentest_menu}}">
                <a href="#">
                    <i class="fa fa-gears"></i> <span>Pentest</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{pentest_new}}">
                        <a href="{{ url_for('autotest.pentest_new') }}">
                            <i class="fa fa-play"></i>New
                        </a>
                    </li>
                    <li class="{{pentest_results}}">
                        <a href="{{ url_for('autotest.pentest_results') }}">
                            <i class="fa fa-list"></i>Results
                        </a>
                    </li>
                </ul>
            </li>
            <!-- /.Petest Menu -->
            <!-- Profile Menu -->
            <li class="{{profile_menu}}">
                <a href="{{ url_for('auth.profile') }}">
                    <i class="fa fa-user"></i>
                    <span>Profile</span>
                </a>
            </li>
            <!-- /.Profile Menu -->
            <!-- Documentation Menu -->
            <li class="{{doc_menu}}">
                <a href="{{ url_for('main.documentation') }}">
                    <i class="fa fa-book"></i>
                    <span>Documentation</span>
                </a>
            </li>
            <!-- /.Documentation Menu -->
            <li class="header"></li>
            <!-- Developers Menu -->
            <li class="{{dev_menu}}">
                <a href="{{ url_for('main.developers') }}">
                    <i class="fa fa-legal"></i>
                    <span>About Developers</span>
                </a>
            </li>
            <!-- /.Developers Menu -->
        </ul>
        <!-- /.sidebar-menu -->
    </section>
</aside>
<!-- /.Main Sidebar -->