mantra/mod_pentest/controllers.py
# Penetration testing module for Mantra Application

# ==================== #
#     Requirements     #
# ==================== #

# Import json module
import json
# Import Thread module
from threading import Thread

# Import pdfkit module
import pdfkit
# Import requests module
import requests
# Import dependencies from flask module
from flask import (Blueprint, abort, flash, jsonify, make_response, redirect,
                   render_template, url_for)
# Import requirement of session management
from flask_login import current_user, login_required

# Import elements from Mantra Application
from mantra import db
# Import forms required in the module
from mantra.mod_pentest.forms import PentestForm
# Import utilities required in the module
from mantra.mod_pentest.utils import Scanner
# Import models required in the module
from mantra.models import ScannedWeb, ScannedWebSchema
# Import url host and port
from run import host, port

# ==================== #


# Define the blueprint: 'autotest', set its url prefix: app.url/autotest
mod_pentest = Blueprint('autotest', __name__, url_prefix='/autotest')


# Set the routes and accepted methods

# ========================= #
#     New Pentest Route     #
# ========================= #
@mod_pentest.route('/pentest_new', methods=['GET', 'POST'])
@login_required
def pentest_new():
    form = PentestForm()
    if form.validate_on_submit():
        data_title = form.title.data
        data_url = form.url.data
        if not (data_url.startswith('http://') or data_url.startswith('https://')):
            flash(f"Invalid URL!", 'danger')
            return redirect(url_for('autotest.pentest_results'))
        data_description = form.description.data
        user_token = current_user.user_token
        data = {"title": data_title,
                "url": data_url,
                "description": data_description,
                "user_token": user_token}
        Thread(target=Scanner.scan, args=(data,)).start()
        flash(f"Pentest is being conducted. Please check the result.", 'warning')
        return redirect(url_for('autotest.pentest_results'))
    return render_template('pentest/pentest_new.html', title='Pentest',
                           pentest_menu='active', pentest_new='active',
                           icons='gears', form=form)


# ========================= #
#     All Results Route     #
# ========================= #
@mod_pentest.route('/pentest_results')
@login_required
def pentest_results():
    return render_template('pentest/pentest_results.html', title='Pentest',
                           pentest_menu='active', pentest_results='active',
                           icons='gears')


# ============================ #
#     Pentest Result Route     #
# ============================ #
@mod_pentest.route('/pentest_result/<web_id>')
@login_required
def pentest_result(web_id):
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    else:
        if web.platform.type == 'wordpress':
            return render_template('pentest/wp_pentest_result.html', title='Pentest',
                                   pentest_menu='active', pentest_results='active',
                                   icons='gears', web=web)
        elif web.platform.type == 'joomla':
            return render_template('pentest/joom_pentest_result.html', title='Pentest',
                                   pentest_menu='active', pentest_results='active',
                                   icons='gears', web=web)


# =========================================== #
#     Retrieves All Results Data from API     #
# =========================================== #
@mod_pentest.route('/get_results_data')
@login_required
def get_all_data():
    scanned_webs_schema = ScannedWebSchema(many=True)
    all_webs = current_user.scanned_webs
    result = scanned_webs_schema.dump(all_webs).data
    sent = jsonify(data=result)
    return sent


# ======================================= #
#     Retrieves raw_result of the web     #
# ======================================= #
@mod_pentest.route('/get_raw_result/<web_id>')
@login_required
def get_one_result(web_id):
    scanned_web_schema = ScannedWebSchema()
    data = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    web = scanned_web_schema.dump(data).data
    raw_result = web['raw_result']
    result = json.loads(raw_result)
    sent = jsonify(result)
    return sent


# =================================== #
#     Delete Pentest Result Route     #
# =================================== #
@mod_pentest.route('/pentest_delete/<web_id>', methods=['POST'])
@login_required
def pentest_delete(web_id):
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    db.session.delete(web)
    db.session.commit()
    flash(f"Pentest result has been deleted!", 'success')
    return redirect(url_for('autotest.pentest_results'))


# =============================== #
#     Create PDF Result Route     #
# =============================== #
@mod_pentest.route("/to_pdf/<web_id>")
@login_required
def to_pdf(web_id):
    domain = f"{host}:{port}"
    scanned_web_schema = ScannedWebSchema()
    web = ScannedWeb.query.filter_by(scan_id=web_id).first_or_404()
    if web.tester != current_user:
        abort(403)
    else:
        if web.platform.type == 'wordpress':
            data = scanned_web_schema.dump(web).data
            raw_result = data['raw_result']
            result = json.dumps(raw_result)
            rendered = render_template(
                'pentest/to_wp_pdf.html', web=web, result=result, domain=domain)
        elif web.platform.type == 'joomla':
            data = scanned_web_schema.dump(web).data
            raw_result = data['raw_result']
            result = json.dumps(raw_result)
            rendered = render_template(
                'pentest/to_joom_pdf.html', web=web, result=result, domain=domain)

        pdf = pdfkit.from_string(rendered, False)
        response = make_response(pdf)
        response.headers['Content-Type'] = 'application/pdf'
        # response.headers['Content-Disposition'] = f'inline; filename={web_id}.pdf'
        response.headers['Content-Disposition'] = f'attachment; filename={web_id}.pdf'

        return response

mantra/templates/pentest/joom_pentest_result.html
{% extends "display/section_etc.html" %}
{% block content %}
    <!-- Results Page -->
    <section class="invoice">
        <!-- Title -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-gears"></i> {{ web.scan_id }}
                    <small class="pull-right">Date: {{ web.date_created.strftime('%d %B %Y') }}</small>
                </h2>
            </div>
        </div>
        <!-- /.Title -->
        <!-- Info -->
        <div class="row invoice-info">
            <div class="col-sm-6 invoice-col">
                <strong>Web Details:</strong>
                <address>
                    Title: {{ web.title }} <br>
                    Descr: {{ web.description }} <br>
                    Type: {{ web.platform.type }} <br>
                    URL: {{ web.url }}
                </address>
            </div>
            <div class="col-sm-6 invoice-col">
                <strong>Tester:</strong>
                <address>
                    Username: {{ web.tester.username }} <br>
                    Email: {{ web.tester.email }}
                </address>
            </div>
        </div>
        <!-- /.Info -->
        <!-- Results row -->
        <div class="row">
            <!-- Theme -->
            <div class="col-xs-12 table-responsive">
                <p class="lead">Result</p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody id="joomResultTable"></tbody>
                </table>
            </div>
        </div>
        <!-- /.Results row -->
    </section>
    <!-- /.Results Page -->
{% endblock %}


{% block script %}
    <script>
        $(document).ready(function (event) {
            let url = `{{url_for('autotest.get_one_result', web_id = web.scan_id)}}`
            getRawDataJoom(url);
        });

        function getRawDataJoom(source) {
            $.getJSON(source, function (data) {
                // Main Theme
                if ($.isEmptyObject(data)) {
                    $("#joomResultTable").append(`
                        <tr><td>None</td></tr>
                    `);
                } else {
                    console.log(data);
                    $("#joomResultTable").append(`
                        <tr>
                            <td>
                                ${data}
                            </td>
                        </tr>
                    `);
                }
                // ./Main Theme
            });
        }
    </script>
{% endblock %}

mantra/templates/pentest/pentest_new.html
{% extends "display/section_content.html" %}
{% block content %}
    <!-- Pentest Page -->
    <div class="box box-primary">
        <!-- Page Title -->
        <div class="box-header with-border">
            <h3 class="box-title">
                {{title}}<small> | Let's test your web security</small>
            </h3>
        </div>
        <!-- Page Body -->
        <div class="box-body">
            <!-- Import render_field -->
            {% from "includes/_formHelper.html" import render_field %}
            <!-- Pentest Form -->
            <form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}

                <!-- Input Title -->
                <div class="form-group">
                    {{ form.title.label(class="col-sm-2 control-label") }}
                    <div class="col-sm-10">
                        {{render_field(form.title, class="form-control",
                            placeholder="Title", title="Title")}}
                    </div>
                </div>

                <!-- Input URL -->
                <div class="form-group">
                    {{ form.url.label(class="col-sm-2 control-label") }}
                    <div class="col-sm-10">
                        {{render_field(form.url, class="form-control",
                            placeholder="URL", title="URL")}}
                    </div>
                </div>

                <!-- Input Description -->
                <div class="form-group">
                    {{ form.description.label(class="col-sm-2 control-label") }}
                    <div class="col-sm-10">
                        {{render_field(form.description, class="form-control",
                            style="resize:none",
                            placeholder="Description", title="Description")}}
                    </div>
                </div>

                <!-- Submit Button -->
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        {{ form.submit(class="btn btn-danger") }}
                    </div>
                </div>
            </form>
            <!-- Pentest Form -->
        </div>
    </div>
    <!-- /.Pentest Page -->
{% endblock %}

mantra/templates/pentest/pentest_results.html
{% extends "display/section_content.html" %}

{% block css %}
    <link rel="stylesheet" type="text/css"
        href="{{url_for('static', filename='bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}">
{% endblock %}


{% block content %}
    <!-- Pentest Results Page -->
    <div class="box box-primary">
        <!-- Page Title -->
        <div class="box-header">
            <h3 class="box-title">
                {{title}}<small> | Results Table</small>
            </h3>
        </div>
        <!-- Page Body -->
        <div class="box-body table-responsive">
            <table id="allResultsTable" class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Description</th>
                        <th>Platform</th>
                        <th>URL</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Actions</th>
                    </tr>
                </thead>
            </table>
        </div>
    </div>

    <!-- Delete Modal -->
    <div id="show-modal">
    </div>
    <!-- Delete Modal -->
{% endblock %}


{% block script %}
    <script src="{{url_for('static', filename='bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
    <script
        src="{{url_for('static', filename='bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script>
    <script>
        $(document).ready(function (event) {
            let url = "{{ url_for('autotest.get_all_data') }}"
            getAllResultsData(url);
        });
        
        function getAllResultsData(source) {
            $(document).ready(function () {
                let t = $('#allResultsTable').DataTable({
                    "searching": true,
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bInfo": false,
                    "bAutoWidth": false,
                    "ajax": {
                        "url": source,
                        "dataType": "json",
                        "dataSrc": "data",
                        "contentType": "application/json"
                    },
                    "order": [[5, 'desc']],
                    "columns": [
                        { "searchable": false, "orderable": false, "data": null },
                        { "data": "title" },
                        { "data": "description" },
                        { "data": "platform" },
                        {
                            "data": "url",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = '<a target="_blank" href="' + data + '">' + data + '</a>';
                                }
                                return data;
                            }
                        },
                        {
                            "data": "date_created",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = new Date(data), options = { weekday: 'long', month: 'long',
                                                                        day: 'numeric', year: 'numeric' };
                                }
                                return data.toLocaleString('en-GB', options);
                            }
                        },
                        {
                            "data": "status",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    data = (data === 1) ? "<span class='label label-success'>Completed</span>" 
                                                        : "<span class='label label-warning'>Proccessing</span>";
                                }
                                return data;
                            }
                        },
                        {
                            "orderable": false,
                            "data": "scan_id",
                            "render": function (data, type, row, meta) {
                                if (type === 'display') {
                                    seeResult = (row['status'] === 1) ? 
                                        `<a target='_blank' href='/autotest/pentest_result/${data}'>
                                            <button type="button" class="btn btn-default">Result</button>
                                        </a>` : ``;
                                    toPDF = (row['status'] === 1) ? 
                                        `<a target='_blank' href='/autotest/to_pdf/${data}'>
                                            <button type="button" class="btn btn-primary">PDF</button>
                                        </a>` : ``;
                                    deleteBtn = `<a href="#">
                                                    <button onclick="showModal('${row['title']}', '${row['url']}',
                                                            '${row['platform']}', '${data}')"
                                                            type="button" class="btn btn-danger">
                                                        Delete
                                                    </button>
                                                </a>`;
                                    data = (`
                                        <div class="btn-group">
                                            ${seeResult}
                                            ${toPDF}
                                            ${deleteBtn}
                                        </div>
                                    `);
                                }
                                return data;
                            }
                        },
                    ],
                });
                t.on('order.dt search.dt', function () {
                    t.column(0, { search: 'applied', order: 'applied' }).nodes().each(function (cell, i) {
                        cell.innerHTML = i + 1;
                    });
                }).draw();
            });
        }
        function showModal(title, url, platform, data){
            $('#show-modal').html(`
                <div class="modal fixed-top" id="modal-default" style=" display: block">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" onclick="closeModal()" aria-label="Close">
                                    <span aria-hidden="true">&times;</span></button>
                                <h4 class="modal-title">Delete result?</h4>
                            </div>
                            <div class="modal-body">
                                <p>
                                    Title: ${title}<br>
                                    URL: ${url}<br>
                                    Platform: ${platform}
                                </p>
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-default pull-left" onclick="closeModal()">
                                    Cancel
                                </button>
                                <form action="/autotest/pentest_delete/${data}" method="POST">
                                    <input class="btn btn-danger" type="submit" value="Delete">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            `);
        }
        function closeModal(){
            $('#show-modal').html(``);
        }
    </script>
{% endblock %}

mantra/templates/pentest/to_joom_pdf.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- CSS file -->
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet"
        href="http://{{domain}}/static/bower_components/bootstrap/dist/css/bootstrap.css">
    <!-- Font Awesome 4.7.0 -->
    <link rel="stylesheet"
        href="http://{{domain}}/static/bower_components/font-awesome/css/font-awesome.css">
    <!-- Ionicons v2.0.0 -->
    <link rel="stylesheet" href="http://{{domain}}/static/bower_components/Ionicons/css/ionicons.css">
    <!-- Theme style v2.4.8 -->
    <link rel="stylesheet" href="http://{{domain}}/static/dist/css/AdminLTE.css">
    <!-- AdminLTE Skins -->
    <link rel="stylesheet" href="http://{{domain}}/static/dist/css/skins/skin-black.css">

    <title>Mantra</title>
</head>

<body class="hold-transition skin-black fixed sidebar-mini {{ adds }}">
    <!-- Results Page -->
    <section class="invoice">
        <!-- Title -->
        <div class="row">
            <div class="col-xs-12">
                <h2 class="page-header">
                    <i class="fa fa-gears"></i> {{ web.scan_id }}
                    <small class="pull-right">Date: {{ web.date_created.strftime('%d %B %Y') }}</small>
                </h2>
            </div>
        </div>
        <!-- /.Title -->
        <!-- Info -->
        <div class="row invoice-info">
            <div class="col-sm-6 invoice-col">
                <strong>Web Details:</strong>
                <address>
                    Title: {{ web.title }} <br>
                    Descr: {{ web.description }} <br>
                    Type: {{ web.platform.type }} <br>
                    URL: {{ web.url }}
                </address>
            </div>
            <div class="col-sm-6 invoice-col">
                <strong>Tester:</strong>
                <address>
                    Username: {{ web.tester.username }} <br>
                    Email: {{ web.tester.email }}
                </address>
            </div>
        </div>
        <!-- /.Info -->
        <!-- Results row -->
        <div class="row">
            <!-- Theme -->
            <div class="col-xs-12 table-responsive">
                <p class="lead">Result</p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>Details</th>
                        </tr>
                    </thead>
                    <tbody id="joomResultTable"></tbody>
                </table>
            </div>
        </div>
        <!-- /.Results row -->
    </section>
    <!-- /.Results Page -->

    <!-- Script file -->
    <!-- jQuery v3.3.1 -->
    <script src="http://{{domain}}/static/bower_components/jquery/dist/jquery.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="http://{{domain}}/static/bower_components/bootstrap/dist/js/bootstrap.js"></script>
    <!-- SlimScroll 1.3.8 -->
    <script
        src="http://{{domain}}/static/bower_components/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- FastClick -->
    <script src="http://{{domain}}/static/bower_components/fastclick/lib/fastclick.js"></script>
    <!-- AdminLTE App 2.4.8 -->
    <script src="http://{{domain}}/static/dist/js/adminlte.js"></script>
    <script>
        $(document).ready(function (event) {
            let raw_result = `{{result}}`;
            let replaced = raw_result.replace(/&#39;/g, "'").replace(/&#34;/g, '"')
                .replace(/&lt;/g,'<').replace(/&gt;/g,'>');
            let cutString = replaced.substr(1).slice(0,-1);
            console.log(cutString);
            let tojson = JSON.parse(cutString);
            let report = getJoomReport(tojson);
        });
        
        function getJoomReport(data) {
            // Main Theme
            if ($.isEmptyObject(data)) {
                $("#joomResultTable").append(`
                    <tr><td>None</td></tr>
                `);
            } else {
                console.log(data);
                $("#joomResultTable").append(`
                    <tr>
                        <td>
                            ${data}
                        </td>
                    </tr>
                `);
            }
            // ./Main Theme
        }
    </script>
</body>

</html>